# Generated by Django 5.2.6 on 2025-09-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_titel',
            new_name='blog_title',
        ),
    ]
